source 'http://gitlab.mogujie.org/ios-team/cocoapods-official-specs-mirror.git'

platform :ios, '8.0'

use_frameworks!
target 'AwesomeCommand_Example' do
  pod 'AwesomeCommand', :path => '../'
end
  target 'AwesomeCommand_Tests' do
  pod 'AwesomeCommand', :path => '../'
end
