source 'https://github.com/cocoapods/specs.git'
platform :ios, '8.0'

target 'kZMoonCommand' do
  pod 'kZMoonCommand', :path => '../'
end
  target 'kZMoonCommandTests' do
  pod 'kZMoonCommand', :path => '../'
end
